-- MySQL Script generated by MySQL Workbench
-- Sun Apr 11 11:47:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema campus_eats_fall2020
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `campus_eats_fall2020` ;

-- -----------------------------------------------------
-- Schema campus_eats_fall2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campus_eats_fall2020` DEFAULT CHARACTER SET utf8 ;
USE `campus_eats_fall2020` ;

-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`person` (
  `person_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_name` VARCHAR(300) NULL DEFAULT NULL,
  `person_email` VARCHAR(150) NULL DEFAULT NULL,
  `cell` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 206
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`major` (
  `major_id` INT NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_id`),
  UNIQUE INDEX `major_id_UNIQUE` (`major_id` ASC) VISIBLE,
  UNIQUE INDEX `major_UNIQUE` (`major` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`type` (
  `type_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `type_id_UNIQUE` (`type_id` ASC) VISIBLE,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`driver` (
  `driver_id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `license_number` VARCHAR(75) NULL DEFAULT NULL,
  `date_hired` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`driver_id`),
  INDEX `fk_D_student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_D_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `campus_eats_fall2020`.`student` (`student_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`student` (
  `student_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `graduation_year` INT(4) NULL DEFAULT NULL,
  `major_id` INT NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_St_person_id` (`person_id` ASC) VISIBLE,
  INDEX `major_id_idx` (`major_id` ASC) VISIBLE,
  INDEX `type_id_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_St_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`),
  CONSTRAINT `major_id`
    FOREIGN KEY (`major_id`)
    REFERENCES `campus_eats_fall2020`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `campus_eats_fall2020`.`type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `campus_eats_fall2020`.`driver` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 152
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`vehicle` (
  `vehicle_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_plate` VARCHAR(75) NULL DEFAULT NULL,
  `make_model_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`vehicle_id`),
  INDEX `make_model_id_idx` (`make_model_id` ASC) VISIBLE,
  CONSTRAINT `make_model_id`
    FOREIGN KEY (`make_model_id`)
    REFERENCES `campus_eats_fall2020`.`make_model` (`make_model_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`delivery` (
  `delivery_id` INT(11) NOT NULL AUTO_INCREMENT,
  `driver_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  `delivery_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `fk_delivery_driver_id` (`driver_id` ASC) VISIBLE,
  INDEX `fk_delivery_vehicle_id` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `campus_eats_fall2020`.`driver` (`driver_id`),
  CONSTRAINT `fk_delivery_vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `campus_eats_fall2020`.`vehicle` (`vehicle_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`title` (
  `title_id` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`title_id`),
  UNIQUE INDEX `title_id_UNIQUE` (`title_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`degree` (
  `degree_id` INT NOT NULL,
  `degree` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`degree_id`),
  UNIQUE INDEX `degree_id_UNIQUE` (`degree_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`faculty` (
  `faculty_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `title_id` INT NULL DEFAULT NULL,
  `degree_college_id` INT NULL DEFAULT NULL,
  `highest_degree_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`faculty_id`),
  INDEX `fk_F_person_id` (`person_id` ASC) VISIBLE,
  INDEX `title_id_idx` (`title_id` ASC) VISIBLE,
  INDEX `highest_degree_id_idx` (`highest_degree_id` ASC) VISIBLE,
  INDEX `degree_college_id_idx` (`degree_college_id` ASC) VISIBLE,
  CONSTRAINT `fk_F_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`),
  CONSTRAINT `title_id`
    FOREIGN KEY (`title_id`)
    REFERENCES `campus_eats_fall2020`.`title` (`title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `degree_college_id`
    FOREIGN KEY (`degree_college_id`)
    REFERENCES `campus_eats_fall2020`.`degree_college` (`degree_college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `highest_degree_id`
    FOREIGN KEY (`highest_degree_id`)
    REFERENCES `campus_eats_fall2020`.`degree` (`degree_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`location` (
  `location_id` INT(11) NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(75) NULL DEFAULT NULL,
  `location_address` VARCHAR(75) NULL DEFAULT NULL,
  `latitude` FLOAT NULL DEFAULT NULL,
  `longitude` FLOAT NULL DEFAULT NULL,
  `drop_off_point` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  UNIQUE INDEX `location_index_desc` (`location_id` ASC) VISIBLE,
  INDEX `idx_location_location_name` (`location_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`restaurant` (
  `restaurant_id` INT(11) NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(75) NULL DEFAULT NULL,
  `restaurant_name` VARCHAR(75) NULL DEFAULT NULL,
  `schedule` VARCHAR(75) NULL DEFAULT NULL,
  `website` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`driver_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`driver_rating` (
  `driver_rating_id` INT NOT NULL,
  `driver_rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`driver_rating_id`),
  UNIQUE INDEX `driver_rating_id_UNIQUE` (`driver_rating_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`rating` (
  `rating_id` INT NOT NULL,
  `restaurant_rating_id` INT NULL DEFAULT NULL,
  `overall_rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`rating_id`),
  CONSTRAINT `restaruant_rating_id`
    FOREIGN KEY (`rating_id`)
    REFERENCES `campus_eats_fall2020`.`rating` (`rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `driver_rating_id`
    FOREIGN KEY (`rating_id`)
    REFERENCES `campus_eats_fall2020`.`driver_rating` (`driver_rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`order` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `delivery_id` INT(11) NOT NULL,
  `location_id` INT(11) NOT NULL,
  `restaurant_id` INT(11) NOT NULL,
  `total_price` FLOAT NOT NULL,
  `delivery_charge` FLOAT NULL DEFAULT NULL,
  `rating_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_O_person_id` (`person_id` ASC) VISIBLE,
  INDEX `fk_O_delivery_id` (`delivery_id` ASC) VISIBLE,
  INDEX `fk_O_location_id` (`location_id` ASC) VISIBLE,
  INDEX `fk_O_restaurant_id` (`restaurant_id` ASC) VISIBLE,
  INDEX `fk_O_rating_id_idx` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `fk_O_delivery_id`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `campus_eats_fall2020`.`delivery` (`delivery_id`),
  CONSTRAINT `fk_O_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `campus_eats_fall2020`.`location` (`location_id`),
  CONSTRAINT `fk_O_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`),
  CONSTRAINT `fk_O_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `campus_eats_fall2020`.`restaurant` (`restaurant_id`),
  CONSTRAINT `fk_O_rating_id`
    FOREIGN KEY (`rating_id`)
    REFERENCES `campus_eats_fall2020`.`rating` (`rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`position` (
  `position_id` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`position_id`),
  UNIQUE INDEX `position_id_UNIQUE` (`position_id` ASC) VISIBLE,
  UNIQUE INDEX `position_UNIQUE` (`position` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`staff` (
  `staff_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NULL DEFAULT NULL,
  `position_id` INT NULL DEFAULT NULL,
  `is_admin` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`staff_id`),
  INDEX `fk_S_person_id` (`person_id` ASC) VISIBLE,
  INDEX `position_id_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_S_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`),
  CONSTRAINT `position_id`
    FOREIGN KEY (`position_id`)
    REFERENCES `campus_eats_fall2020`.`position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`degree_college`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`degree_college` (
  `degree_college_id` INT NOT NULL,
  `degree_college` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`degree_college_id`),
  UNIQUE INDEX `degree_college_UNIQUE` (`degree_college_id` ASC) VISIBLE,
  CONSTRAINT `faculty`
    FOREIGN KEY (`degree_college_id`)
    REFERENCES `campus_eats_fall2020`.`faculty` (`degree_college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`make_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`make_model` (
  `idmake_model` INT NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`idmake_model`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`make_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`make_model` (
  `idmake_model` INT NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`idmake_model`))
ENGINE = InnoDB;

USE `campus_eats_fall2020` ;

-- -----------------------------------------------------
-- Placeholder table for view `campus_eats_fall2020`.`person_join`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`person_join` (`person_id` INT, `person_name` INT, `person_email` INT, `student_id` INT, `graduation_year` INT);

-- -----------------------------------------------------
-- Placeholder table for view `campus_eats_fall2020`.`person_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`person_student` (`person_id` INT, `person_name` INT, `person_email` INT, `cell` INT);

-- -----------------------------------------------------
-- View `campus_eats_fall2020`.`person_join`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campus_eats_fall2020`.`person_join`;
USE `campus_eats_fall2020`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `campus_eats_fall2020`.`person_join` AS select `campus_eats_fall2020`.`person`.`person_id` AS `person_id`,`campus_eats_fall2020`.`person`.`person_name` AS `person_name`,`campus_eats_fall2020`.`person`.`person_email` AS `person_email`,`campus_eats_fall2020`.`student`.`student_id` AS `student_id`,`campus_eats_fall2020`.`student`.`graduation_year` AS `graduation_year` from (`campus_eats_fall2020`.`person` join `campus_eats_fall2020`.`student` on((`campus_eats_fall2020`.`student`.`person_id` = `campus_eats_fall2020`.`person`.`person_id`))) where (`campus_eats_fall2020`.`student`.`major` = 'Computer Science');

-- -----------------------------------------------------
-- View `campus_eats_fall2020`.`person_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campus_eats_fall2020`.`person_student`;
USE `campus_eats_fall2020`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `campus_eats_fall2020`.`person_student` AS select `a`.`person_id` AS `person_id`,`a`.`person_name` AS `person_name`,`a`.`person_email` AS `person_email`,`a`.`cell` AS `cell` from `campus_eats_fall2020`.`person` `a` where `a`.`person_id` in (select `campus_eats_fall2020`.`student`.`person_id` from `campus_eats_fall2020`.`student` where (`campus_eats_fall2020`.`student`.`graduation_year` = 2019));
USE `campus_eats_fall2020`;

DELIMITER $$
USE `campus_eats_fall2020`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `campus_eats_fall2020`.`order_AFTER_INSERT`
AFTER INSERT ON `campus_eats_fall2020`.`order`
FOR EACH ROW
BEGIN
	insert into niner_eats.delivery (driver_id, vehicle_id) values(new.driver_id, 2);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
